name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: 0 0 * * *

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Calcualte coverage
      run: |
        go test -v -covermode=count -coverprofile=covprofile
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.github_token }}
      run: goveralls -coverprofile=covprofile -service=github
